version: '3.8'
services:
  nuxt-app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      - NODE_ENV=${NODE_ENV:-development}
    networks:
      - sec-net
networks:
  sec-net:
    driver: bridge
